### ISSUE TITLE
Fabric -  Crashlytics

### ISSUE THREAD

**Issue by pinkred** [Appboy/appboy-android-sdk#104]
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?

Android OS 4.4.2(only)
braze sdk : 'com.appboy:android-sdk-ui:2.4.+'

Fatal Exception: java.lang.IllegalArgumentException: Comparison method violates its general contract!
       at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:831)
       at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:449)
       at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:388)
       at java.util.ComparableTimSort.sort(ComparableTimSort.java:187)
       at java.util.ComparableTimSort.sort(ComparableTimSort.java:142)
       at java.util.Arrays.sort(Arrays.java:1970)
       at java.util.Collections.sort(Collections.java:1864)
       at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:6669)
       at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:6634)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2503)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.widget.RelativeLayout.dispatchPopulateAccessibilityEvent(RelativeLayout.java:1098)
       at android.widget.RelativeLayout.dispatchPopulateAccessibilityEvent(RelativeLayout.java:1098)
       at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2509)
       at android.view.View.dispatchPopulateAccessibilityEvent(View.java:5033)
       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:4998)
       at android.view.View.sendAccessibilityEventUnchecked(View.java:4982)
       at android.view.View.sendAccessibilityEventInternal(View.java:4959)
       at android.view.View.sendAccessibilityEvent(View.java:4928)
       at android.view.View.onFocusChanged(View.java:4861)
       at android.view.View.handleFocusGainInternal(View.java:4666)
       at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:609)
       at android.view.View.requestFocusNoSearch(View.java:7055)
       at android.view.View.requestFocus(View.java:7034)
       at android.view.ViewGroup.requestFocus(ViewGroup.java:2381)
       at android.view.View.requestFocus(View.java:7001)
       at android.view.View.requestFocus(View.java:6980)
       at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:2987)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:655)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:655)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:655)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:655)
       at android.view.View.setFlags(View.java:9043)
       at android.view.View.setFocusableInTouchMode(View.java:6163)
       at com.appboy.ui.support.ViewUtils.removeViewFromParent(ViewUtils.java:21)
       at com.appboy.ui.inappmessage.InAppMessageViewWrapper.closeInAppMessageView(InAppMessageViewWrapper.java:380)
       at com.appboy.ui.inappmessage.InAppMessageViewWrapper.access$900(InAppMessageViewWrapper.java:27)
       at com.appboy.ui.inappmessage.InAppMessageViewWrapper$9.onAnimationEnd(InAppMessageViewWrapper.java:360)
       at android.view.animation.Animation$3.run(Animation.java:374)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5094)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by radixdev** [comment]
Hello @pinkred, do you have any steps to reproduce the issue? What device was this issue seen on?

**Comment by pinkred** [comment]
Sorry, I don't know any stpes, only has issue reports.  It occurs in various devices, Samsung, LG etc. but all device is android version 4.4.2. The issue occurs about 60 times a month. 
App : https://play.google.com/store/apps/details?id=com.twoheart.dailyhotel

**Comment by radixdev** [comment]
We have a fix written, which should be released in our next update.

**Comment by radixdev** [comment]
Fixed in 2.5.1
