### ISSUE TITLE
CertificateExpiredException in Android 9 (P)

### ISSUE THREAD

**Issue by waliahimanshu** [Appboy/appboy-android-sdk#108]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
 2.1.3,
We are still using GCM, so can not migrate to latest version.

## What did you do?
While launching the app 

## What did you expect to happen?
 To not see this exception and seen braze in app message feed

## What happened instead?
 
 bo.app.ar: Could not set up connection [https://trianguli.api.appboy.eu/api/v3/data] [Chain validation failed].  Appboy will try to reconnect periodically.
        at bo.app.c.b(SourceFile:138)
        at bo.app.c.a(SourceFile:75)
        at bo.app.c.a(SourceFile:57)
        at bo.app.c.a(SourceFile:48)
        at bo.app.h.a(SourceFile:36)
        at bo.app.f.a(SourceFile:34)
        at bo.app.cm.a(SourceFile:88)
        at bo.app.cm.run(SourceFile:61)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
        at bo.app.c.a(SourceFile:152)
        at bo.app.c.b(SourceFile:135)
        at bo.app.c.a(SourceFile:75) 
        at bo.app.c.a(SourceFile:57) 
        at bo.app.c.a(SourceFile:48) 
        at bo.app.h.a(SourceFile:36) 
        at bo.app.f.a(SourceFile:34) 
        at bo.app.cm.a(SourceFile:88) 
        at bo.app.cm.run(SourceFile:61) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertificateException: Chain validation failed
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192) 
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149) 
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) 
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) 
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) 
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26) 
        at bo.app.c.a(SourceFile:152) 
        at bo.app.c.b(SourceFile:135) 
        at bo.app.c.a(SourceFile:75) 
        at bo.app.c.a(SourceFile:57) 
        at bo.app.c.a(SourceFile:48) 
        at bo.app.h.a(SourceFile:36) 
        at bo.app.f.a(SourceFile:34) 
        at bo.app.cm.a(SourceFile:88) 
        at bo.app.cm.run(SourceFile:61) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:703)
        	... 38 more
     Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Fri Sep 28 16:38:27 GMT+02:00 2018 (compared to Sat Oct 13 14:34:29 GMT+02:00 2018)
        at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:266)
        at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
        at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        	... 43 more
10-13 14:34:29.348 7949-8143/com.thetrainline.debug E/Appboy v2.1.3 .bo.app.cl: Error occurred while executing Appboy request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.
10-13 14:34:29.350 7949-8156/com.thetrainline.debug I/Appboy v2.1.3 .bo.app.fp: 1539434069 seconds have passed since the last trigger action (minimum interval: 0).
1

**Comment by Bucimis** [comment]
Hi @waliahimanshu,

What's the device time on the phone?

```
Certificate expired at Fri Sep 28 16:38:27 GMT+02:00 2018 (compared to Sat Oct 13 14:34:29 GMT+02:00 2018)
```

It appears the device reported it's own time as Oct 13 2018 - after our current cert is set to expire.

**Comment by waliahimanshu** [comment]
Hi, thanks for the quick reply.
Didn't realise that correct time was not set, it fixed after setting the correct time.
Closing the issue.
