### ISSUE TITLE
Appboy will not function properly starting with Android 8.1 or later.

### ISSUE THREAD

**Issue by kiwinam** [Appboy/appboy-android-sdk#124]
Appboy will not function properly starting with Android 8.1 or later.
With these messages,

E/Appboy v3.2.1 .bo.app.cw: Error occurred while executing Braze request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.
W/Appboy v3.2.1 .bo.app.cx: Experienced exception processing API response. Failing task.
    bo.app.av: Could not set up connection [https://sdk.iad-03.braze.com/api/v3/data] [Chain validation failed].  Appboy will try to reconnect periodically.
        at bo.app.f.b(SourceFile:139)
        at bo.app.f.a(SourceFile:75)
        at bo.app.f.a(SourceFile:62)
        at bo.app.f.a(SourceFile:53)
        at bo.app.j.a(SourceFile:38)
        at bo.app.h.a(SourceFile:38)
        at bo.app.cx.a(SourceFile:103)
        at bo.app.cx.run(SourceFile:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1477)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1423)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1367)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:489)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at bo.app.f.a(SourceFile:154)
        at bo.app.f.b(SourceFile:136)
        at bo.app.f.a(SourceFile:75) 
        at bo.app.f.a(SourceFile:62) 
        at bo.app.f.a(SourceFile:53) 
        at bo.app.j.a(SourceFile:38) 
        at bo.app.h.a(SourceFile:38) 
        at bo.app.cx.a(SourceFile:103) 
        at bo.app.cx.run(SourceFile:70) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertificateException: Chain validation failed
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:718)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:543)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:564)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:609)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:413)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:381)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:222)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1477) 
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1423) 
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1367) 
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219) 
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142) 
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:489) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0) 
        at bo.app.f.a(SourceFile:154) 
        at bo.app.f.b(SourceFile:136) 
        at bo.app.f.a(SourceFile:75) 
        at bo.app.f.a(SourceFile:62) 
        at bo.app.f.a(SourceFile:53) 
        at bo.app.j.a(SourceFile:38) 
        at bo.app.h.a(SourceFile:38) 
        at bo.app.cx.a(SourceFile:103) 
        at bo.app.cx.run(SourceFile:70) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:133)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
2019-03-25 16:30:05.742 13540-13745/com.getliner.Liner W/Appboy v3.2.1 .bo.app.cx:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
        at com.android.org.conscrypt.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:42)
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:714)
        	... 38 more
     Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
        at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
        at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
        at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
        at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        	... 44 more
    	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
        at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
        at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
        at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
        at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
        at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
        		... 46 more

**Comment by radixdev** [comment]
Hi @kiwinam ,

Can you fill out the [ISSUE TEMPLATE?](https://raw.githubusercontent.com/Appboy/appboy-android-sdk/master/.github/ISSUE_TEMPLATE.md)?
Have you modified your device's time settings?
Are you using certificate pinning?

**Comment by kiwinam** [comment]
OK, @radixdev 

[*] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
[] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
3.2.1

## What did you do?
Define user custom attribute

## What did you expect to happen?
Trying to fill in user information on the Braze.

## What happened instead?
Only user sessions are created and no information is entered.

## Steps to reproduce

- Start the app
- Change to new user
- Try to set user information such as Profile, Recent Devices, Custom Attributes
- Information from users running Android 8.1 and later is not stored.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
appboyInstance.currentUser!!.setFirstName(it.name)
                appboyInstance.currentUser!!.setEmail(it.email)
                appboyInstance.currentUser!!.setLanguage(Locale.getDefault().language.toString())

## Project that demonstrates the issue
http://apps.samsung.com/appquery/appDetail.as?appId=com.getliner.Liner

# ANR Reporting


## Entire ANR Report


## Braze Related Threads In ANR

**Comment by radixdev** [comment]
Have you modified your device's time settings?
Are you using certificate pinning?
Can you provide a direct link to the apk?

You can also email support@braze.com to communicate if this issue involves sensitive material, such as answers to the above questions.

**Comment by gchulsong** [comment]
@kiwinam
저도 동일한 문제를 겪고 있습니다. 혹시 해결 하셨나요??
I have the same problem. Did you solve it ??

**Comment by radixdev** [comment]
Hi @gchulsong 

Have you modified your device's time settings?
Are you using certificate pinning?
Can you provide a direct link to the apk?

You can also email support@braze.com to communicate if this issue involves sensitive material, such as answers to the above questions.

**Comment by gchulsong** [comment]
Hi @radixdev 

Have you modified your device's time settings? => no
Are you using certificate pinning? => no
Can you provide a direct link to the apk? 
=> https://play.google.com/store/apps/details?id=tv.wavmusic.android


We have a "development build version" and a 'production build version'.
'Development build version' works well.
However, there is a problem with the 'production build version'.

The differences between the two versions are:
1. build gradle's minifyEnabled
2. Whether to use proguard
3. apiKey set in AppboyConfig

I am looking at which of these values is affecting.

**Comment by radixdev** [comment]
@gchulsong 

1. What exact device are you testing on? I tested on an Android P device and that app worked fine.
2. Can you share your stacktrace with the error?
3. Can you reproduce on an emulator?
4. What Wifi settings are you on?

**Comment by radixdev** [comment]
I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Comment by rakeshostwal** [comment]
I am having this issue now: 
```
E/Appboy v3.3.0 .bo.app.cw: Error occurred while executing Braze request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.
```

Did it fix in the latest release? How do i fix it? Do I need to update any config setting?

**Comment by radixdev** [comment]
@rakeshostwal Please fill out the new issue template.
