### ISSUE TITLE
Appboy Webview XSS

### ISSUE THREAD

**Issue by phspade** [Appboy/appboy-android-sdk#150]
Hi Team,

The package `com.appboy.ui.AppboyWebViewActivity` is vulnerable in XSS. If a vulnerable android application uses the Appboy SDK, it can execute arbitrary XSS payload through Third-Party apps.

**Malicious Android Code**
```
Intent i = new Intent();
i.setComponent(new ComponentName("<some vulnerable android app>","com.appboy.ui.AppboyWebViewActivity"));
i.putExtra("url","javascript:alert%28%22XSS%22%29");
startActivity(i);
```

**ADB Command**
`adb shell am start -n <some vulnerable android app>/com.appboy.ui.AppboyWebViewActivity -e url 'javascript:
alert%28%22XSS%22%29'`

**Comment by radixdev** [comment]
Hello @phspade ,

I am unable to reproduce the vulnerability you're describing. The class `com.appboy.ui.AppboyWebViewActivity` is not exported (and does not contain an intent-filter) so the Android OS does not make it available to another app on the system. As expected, this is the error thrown by Android when attempting what you stated:

```
2020-01-27 11:35:53.939 ? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appboy.sample, PID: 24821
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appboy.sample/com.appboy.sample.DroidBoyActivity}: java.lang.SecurityException: Permission Denial: starting Intent { cmp=CLIENT_APP_HERE/com.appboy.ui.AppboyWebViewActivity (has extras) } from ProcessRecord{df30a75 24821:com.appboy.sample/u0a1250} (pid=24821, uid=11250) not exported from uid 11233
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Permission Denial: starting Intent { cmp=CLIENT_APP_HERE/com.appboy.ui.AppboyWebViewActivity (has extras) } from ProcessRecord{df30a75 24821:com.appboy.sample/u0a1250} (pid=24821, uid=11250) not exported from uid 11233
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3851)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1712)
        at android.app.Activity.startActivityForResult(Activity.java:5211)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:5169)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:5540)
        at android.app.Activity.startActivity(Activity.java:5508)
        at com.appboy.sample.DroidBoyActivity.onCreate(DroidBoyActivity.java:132)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1058)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:762)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:585)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1298)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:516)
```

As such, I cannot reproduce a vulnerability (showing an alert) with the code you provided.

As for the ADB command, it is expected behavior that a running instance of ADB (to a connected and unlocked device) can execute Activity starts. However, even with that higher level of privilege, that ADB command similarly returns the same permission denial as your code example.
