### ISSUE TITLE
NoClassDefFoundError crash on jetified version

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [Appboy/appboy-android-sdk#164]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

`com.appboy:android-sdk-ui-jetified:7.0.0`

## What did you do?

Just migrated from the `com.appboy:android-sdk-ui:6.0.0` to `com.appboy:android-sdk-ui-jetified:7.0.0`.

## What did you expect to happen?

No crash.

## What happened instead?

`java.lang.NoClassDefFoundErrorcom.appboy.configuration.AppboyConfig$Builder.setApiKey:495`

```
java.lang.NoClassDefFoundError: Invalid descriptor: Lcom/appboy/support/StringUtils*.
        at com.appboy.configuration.AppboyConfig$Builder.setApiKey(AppboyConfig:495)
        at br.com.ifood.libraries.BrazeInitializer.init(BrazeInitializer.kt:19)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6708)
        at android.app.ActivityThread.access$1400(ActivityThread.java:232)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2014)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

## Steps to reproduce

Upgrade braze to `com.appboy:android-sdk-ui-jetified:7.0.0` and build the app in release mode with proguard.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No.

**Comment by guilherme-pereira-ifood** [comment]
We just realized that this is also happening before the migration to `jetified 7.0.0` version.

**Comment by radixdev** [comment]
Hi @guilherme-pereira-ifood ,

We'll need more information on reproduction steps. Can you share your full gradle setup and proguard configuration? Otherwise you can just create a small sample app ([an sscce](http://sscce.org/)) that reproduces the issue and link it here.

**Comment by radixdev** [comment]
Hey @guilherme-pereira-ifood ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
