### ISSUE TITLE
Caused by java.lang.IllegalArgumentException com.appboy.push.NotificationTrampolineActivity.onResume

### ISSUE THREAD

**Issue by pinkredmobile** [Appboy/appboy-android-sdk#179]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

13.1.0

## Project that demonstrates the issue

# ANR Reporting

## Entire ANR Report
Caused by java.lang.IllegalArgumentException
       at android.os.Parcel.nativeAppendFrom(Parcel.java)
       at android.os.Parcel.appendFrom(Parcel.java:462)
       at android.os.BaseBundle.<init>(BaseBundle.java:130)
       at android.os.Bundle.<init>(Bundle.java:102)
       at android.content.Intent.getExtras(Intent.java:5883)
       at com.appboy.push.NotificationTrampolineActivity.onResume(NotificationTrampolineActivity.java:41)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1268)
       at android.app.Activity.performResume(Activity.java:6541)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3435)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3481)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
       at android.app.ActivityThread.access$1100(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:6006)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)

**Comment by pinkredmobile** [comment]
other anr
Caused by java.lang.RuntimeException: Parcel android.os.Parcel@f725298: Unmarshalling unknown type code 1318 at offset 172
       at android.os.Parcel.readValue(Parcel.java:2371)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2645)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.putAll(Bundle.java:182)
       at android.content.Intent.putExtras(Intent.java:6908)
       at com.appboy.push.NotificationTrampolineActivity.onResume(NotificationTrampolineActivity.java:42)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6361)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3149)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by radixdev** [comment]
Hi @pinkredmobile ,

Can you provide reproduction steps?
How many of these exceptions are occuring?
What devices and OS's are these exceptions being seen on?

**Comment by pinkredmobile** [comment]
<img width="829" alt="스크린샷 2021-04-02 오전 8 46 00" src="https://user-images.githubusercontent.com/38870613/113365093-2cbba200-9390-11eb-8d95-effe86468a92.png">
<img width="836" alt="스크린샷 2021-04-02 오전 8 46 18" src="https://user-images.githubusercontent.com/38870613/113365099-2f1dfc00-9390-11eb-9ab5-f33d6715feb7.png">
<img width="832" alt="스크린샷 2021-04-02 오전 8 46 22" src="https://user-images.githubusercontent.com/38870613/113365101-3218ec80-9390-11eb-88a0-36aeeadb1bdb.png">
<img width="827" alt="스크린샷 2021-04-02 오전 8 46 33" src="https://user-images.githubusercontent.com/38870613/113365105-3513dd00-9390-11eb-89e7-939a28e5b691.png">
<img width="820" alt="스크린샷 2021-04-02 오전 8 46 37" src="https://user-images.githubusercontent.com/38870613/113365111-37763700-9390-11eb-8851-5d7449ea9b9a.png">

**Comment by pinkredmobile** [comment]
**others issue**
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 7541342668 byte allocation with 16777216 free bytes and 402MB until OOM
android.util.ArrayMap.allocArrays (ArrayMap.java:198)
android.content.Intent.putExtras (Intent.java:6911)
com.appboy.push.AppboyNotificationUtils.sendPushActionIntent (AppboyNotificationUtils.java:1187)
com.appboy.push.AppboyNotificationUtils.sendNotificationOpenedBroadcast (AppboyNotificationUtils.java:1117)
com.appboy.push.AppboyNotificationUtils.handleNotificationOpened (AppboyNotificationUtils.java:70)
com.appboy.BrazePushReceiver$PushHandlerRunnable.performWork (BrazePushReceiver.java:95)
com.appboy.BrazePushReceiver$PushHandlerRunnable.run (BrazePushReceiver.java:65)
java.lang.Thread.run (Thread.java:818)

**Comment by radixdev** [comment]
Hi @pinkredmobile ,

This appears to be [this issue](https://stackoverflow.com/questions/63225930/getintent-getextras-sometimes-crashing-in-activity) and is a result of a bug in the Android OS before 8. We'll wrap that code in a try/catch in the next release.

**Comment by radixdev** [comment]
Hi @pinkredmobile ,

A fix for this has been released in 13.1.2 of the SDK. Thank you for filing!
