### ISSUE TITLE
AppboyWebViewActivity or BrazeWebViewActivity fails/error when handling url with `intent://` scheme.

### ISSUE THREAD

**Issue by ha-yi** [Appboy/appboy-android-sdk#201]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# AppboyWebViewActivity or BrazeWebViewActivity fails/error when handling url with `intent://` scheme.

## What version of the Braze Android SDK are you using?
14.0.1

## What did you do?

I am using the braze cordova SDK, but this issues is specifically happened only in android and coming from this version.

I have encounter an error when opening the firebase deeplinks like this:

```
8-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=intent://link.esample.com/?link=https://example.com/some/path flg=0x34000000 (has extras) }
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2066)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Activity.startActivityForResult(Activity.java:5277)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Activity.startActivityForResult(Activity.java:5235)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Activity.startActivity(Activity.java:5606)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.Activity.startActivity(Activity.java:5574)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at com.appboy.ui.actions.UriAction.openUriWithActionView(UriAction.java:137)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at com.appboy.ui.actions.UriAction.execute(UriAction.java:85)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at com.appboy.ui.AppboyWebViewActivity$2.handleUrlOverride(AppboyWebViewActivity.java:130)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at com.appboy.ui.AppboyWebViewActivity$2.shouldOverrideUrlLoading(AppboyWebViewActivity.java:93)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-451511534:14)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.os.MessageQueue.next(MessageQueue.java:336)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.os.Looper.loop(Looper.java:181)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at android.app.ActivityThread.main(ActivityThread.java:7565)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 16:28:43.847 32601 32601 E Braze v14.0.1 .com.appboy.ui.actions.UriAction: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
```

The canvas that we are using is:
IAM Full Screen with 2 buttons, button 1 onclick behavior is redirect to Web Url with open web url inside app is checked.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/966816/127985914-ac05d4a7-ea9b-4617-bdb7-4529cfa6bd88.png">

## What did you expect to happen?

Should open the deeplink into app or any appririate actions, instead of throwing error.

## What happened instead?

Error.

**Comment by radixdev** [comment]
Hi @ha-yi ,

Please provide steps to reproduce, the actual/unchanged deeplink, and a URL to the Braze campaign. You may email support@braze.com if this forum is too public for that information.

**Comment by ha-yi** [comment]
Ok, sure. 
I also have some commit to solve our current issue: https://github.com/Appboy/appboy-android-sdk/compare/v14.0.1...ha-yi:fix_intent_handling?expand=1

**Comment by radixdev** [comment]
Hi @ha-yi ,

Please provide steps to reproduce, the actual/unchanged deeplink, and a URL to the Braze campaign/canvas, and the Android device used in your testing. This will aide us in our investigation of your issue.

**Comment by radixdev** [comment]
Hey @ha-yi ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
