### ISSUE TITLE
ANR on BrazeCoroutineScope

### ISSUE THREAD

**Issue by arlindiDev** [Appboy/appboy-android-sdk#215]
`BrazeCoroutineScope.kt line 6
com.braze.coroutine.BrazeCoroutineScope.<clinit>`

The crash happens only on Android 11 & Android 12 

* [X] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [x] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## Entire ANR Report
```
main (runnable): tid=1 systid=11493
       at kotlinx.coroutines.Dispatchers.<clinit>(Dispatchers.kt:32)
       at kotlinx.coroutines.Dispatchers.getIO(Dispatchers.kt:134)
       at com.braze.coroutine.BrazeCoroutineScope.<clinit>(SourceFile:6)
       at com.braze.images.DefaultBrazeImageLoader.initDiskCacheTask(SourceFile:1)
       at com.braze.images.DefaultBrazeImageLoader.<init>(SourceFile:10)
       at com.appboy.Appboy.<init>(SourceFile:59)
       at com.braze.Braze.<init>(SourceFile:1)
       at com.appboy.Appboy.getInstance(SourceFile:7)
       at com.braze.Braze.getInstance(SourceFile:1)
       at com.myapp.android.braze.BrazeModule.provideBraze(BrazeModule.java:31)
       at com.myapp.android.braze.BrazeModule_ProvideBrazeFactory.provideBraze(BrazeModule_ProvideBrazeFactory.java:41)
       at com.myapp.android.app.DaggerRealApplicationComponent$SwitchingProvider.get3(DaggerRealApplicationComponent.java:23475)
       at com.myapp.android.app.DaggerRealApplicationComponent$SwitchingProvider.get(DaggerRealApplicationComponent.java:23905)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.myapp.android.app.DaggerRealApplicationComponent.injectRealmyappApplication(DaggerRealApplicationComponent.java:7559)
       at com.myapp.android.app.DaggerRealApplicationComponent.inject(DaggerRealApplicationComponent.java:7335)
       at com.myapp.android.app.RealmyappApplication.inject(RealmyappApplication.java:78)
       at com.myapp.android.myappApplication.onCreate(myappApplication.java:206)
       at com.myapp.android.app.RealmyappApplication.onCreate(RealmyappApplication.java:34)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7545)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7484)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2156)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 ```

**Comment by radixdev** [comment]
Hi @arlindiDev ,

SDK 19.0.0 directly addresses the ANR issues in the SDK. However, the kotlin coroutine issue (https://github.com/Kotlin/kotlinx.coroutines/issues/3180) our team raised is still present so depending on your version of kotlin coroutines you still may continue to see issues.

**Comment by radixdev** [comment]
Hi @arlindiDev ,

Please update your kotlin coroutine version to 1.6.1+ and Braze Android 19.0.0+ to resolve the issue. See https://github.com/Kotlin/kotlinx.coroutines/issues/3180 for more information.
