### ISSUE TITLE
[Bug]: Fatal Exception: java.lang.NoSuchMethodError No virtual method removeSingleSubscription

### ISSUE THREAD

**Issue by zhaojin1229** [Appboy/appboy-android-sdk#230]
### Braze Android SDK Version

22.0.0

### Steps To Reproduce

Encountered this problem each time when open app, it crashes the app
Implemented using flutter braze plugin version as below:
braze_plugin: ^2.3.0

### Expected Behavior

Not crashing the app

### Actual Incorrect Behavior

it crashes the app

### Verbose Logs

```shell
java.lang.NoSuchMethodError: No virtual method removeSingleSubscription(Lcom/appboy/events/IEventSubscriber;Ljava/lang/Class;)V in class Lcom/braze/Braze; or its super classes (declaration of 'com.braze.Braze' appears in /data/app/~~v8Yg_XN0YKNmzjnt6_MwWQ==/base.apk)
        at com.braze.brazeplugin.IntegrationInitializer.subscribeToContentCardsUpdatedEvent(IntegrationInitializer.kt:31)
        at com.braze.brazeplugin.IntegrationInitializer.initializePlugin$braze_plugin_debug(IntegrationInitializer.kt:22)
        at com.braze.brazeplugin.BrazePlugin.onAttachedToActivity(BrazePlugin.kt:137)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:155)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:29)
        at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:1183)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
        at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:743)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8315)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Additional Information

Added the android lib according to braze integration document like below

<img width="590" alt="image (3)" src="https://user-images.githubusercontent.com/2618456/179706156-6bdfb104-0691-416d-bf8e-45fb6f29defa.png">

**Comment by Bucimis** [comment]
@zhaojin1229 the latest Flutter SDK (v2.5.0) supports only up to Braze Android SDK v21.0.0 (https://github.com/braze-inc/braze-flutter-sdk/blob/master/CHANGELOG.md#breaking). Please update your build.gradle to specify 21.0.0 - https://github.com/braze-inc/braze-flutter-sdk/blob/1dfe6fdcee470b3421509de89f15ca42b3d80d25/example/android/app/build.gradle#L83

**Comment by zhaojin1229** [comment]
Thank you @Bucimis
