### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by krishnapatait** [Appboy/appboy-android-sdk#234]
### Braze Android SDK Version

 Android SDK version 23.0.1

### Steps To Reproduce

1. Add SDK to the project by following all the instructions given in: https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#basic-integration
2. Once all is DONE then test the integration
3. It shows the error:  bo.app.o3: Failed request to [https://sdk.iad-06.braze.com/api/v3/data], with the message: [Failed to connect to sdk.iad-06.braze.com/:::443]
4. It always shows and I was not able to view the installation count in the overview section of the dashboard.

### Expected Behavior

API should provide the response.

### Actual Incorrect Behavior

2022-08-26 23:13:30.470 6385-6637/com.example.scan W/Braze v23.0.1 .s: Api response was null, failing task.
2022-08-26 23:13:30.470 6385-6637/com.example.scan W/Braze v23.0.1 .i0: Error occurred while executing Braze request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.

### Verbose Logs

```shell
2022-08-26 23:13:30.470 6385-6637/com.coinout.scan E/Braze v23.0.1 .s: Experienced exception processing API response. Failing task.
    bo.app.o3: Failed request to [https://sdk.iad-06.braze.com/api/v3/data], with message: [Failed to connect to sdk.iad-06.braze.com/:::443]
        at bo.app.p1.a(SourceFile:209)
        at bo.app.j3.a(SourceFile:56)
        at bo.app.s.b(SourceFile:8)
        at bo.app.s.c(SourceFile:2)
        at bo.app.o4.a(SourceFile:26)
        at bo.app.o4.a(SourceFile:1)
        at bo.app.o4$b.invokeSuspend(SourceFile:1)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
     Caused by: java.net.ConnectException: Failed to connect to sdk.iad-06.braze.com/:::443
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at bo.app.p1.a(SourceFile:224)
        at bo.app.p1.a(SourceFile:4)
        at bo.app.j3.a(SourceFile:56) 
        at bo.app.s.b(SourceFile:8) 
        at bo.app.s.c(SourceFile:2) 
        at bo.app.o4.a(SourceFile:26) 
        at bo.app.o4.a(SourceFile:1) 
        at bo.app.o4$b.invokeSuspend(SourceFile:1) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) 
```

**Comment by Bucimis** [comment]
@krishnapatait ```Failed to connect to sdk.iad-06.braze.com/:::443``` is the issue here, I'd make sure your cluster URL is 100% correct + sanitized
