### ISSUE TITLE
[Bug]: gif in-app message NullPointerException

### ISSUE THREAD

**Issue by jihyeh** [Appboy/appboy-android-sdk#245]
### Braze Android SDK Version

22.0.0

### Steps To Reproduce

After sending CE in Activity-onCreate(), braze sends an gif in-app message.

### Expected Behavior

_none_

### Actual Incorrect Behavior

_none_

### Verbose Logs

```shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
       at com.braze.ui.inappmessage.views.InAppMessageModalView.lambda$resizeGraphicFrameIfAppropriate$1(InAppMessageModalView.java:189)
       at com.braze.ui.inappmessage.views.InAppMessageModalView.lambda$resizeGraphicFrameIfAppropriate$1$InAppMessageModalView(InAppMessageModalView.java)
       at com.braze.ui.inappmessage.views.-$$Lambda$InAppMessageModalView$8AaddAoIQK-bDpakGuhpAK6Y-PA.run(lambda:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Additional Information

ImageLoader was created by following the [guide](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/gifs) provided.

**Comment by radixdev** [comment]
Hi @jihyeh ,

1. Can you reproduce this error on the latest SDK version?
2. Can you provide verbose logcat of the error?
3. Can you provide an image for reproducing the error?

**Comment by jihyeh** [comment]
Hi @radixdev 

It is not reproducible and can only be confirmed in the crash report. 
so I will check it again after changing to the latest SDK. thx 🙂
