### ISSUE TITLE
[Bug]: ANR Card.logImpression

### ISSUE THREAD

**Issue by ashraf-patel-hs** [Appboy/appboy-android-sdk#266]
### Braze Android SDK Version

23.2.1

### Steps To Reproduce

Card.logImpression is causing the ANR when performed on the main thread.

### Expected Behavior

NO ANRs or documentation on which thread shall we use to perform such operation

### Actual Incorrect Behavior

It's causing an ANR

main (waiting):tid=1 systid=3971 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
       at java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
       at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
       at bo.app.p.a(SourceFile:10)
       at com.appboy.models.cards.Card.logImpression(SourceFile:5)

### Additional Information

Are we supposed to execure Card.logImpression on the UI thread?

**Comment by bryanlogan** [comment]
It should run just fine there. Can you provide verbose logs as well, along with any other stacks that contain Braze in the stack at the time of the crash? 

If you don't want to provide those via GitHub, then go through Braze support so we can handle it there.

**Comment by ashraf-patel-hs** [comment]
@bryanlogan thanks for the reply. That's all we get related to braze, starts from braze's `Card.logImpression` is called from our codebase, inside a fragment which causes the ANR. 

Could you please give me a hint on what other logs you need?

**Comment by bryanlogan** [comment]
The output of "adb" contains other Braze information.  You can add "BrazeLogger.logLevel = Log.VERBOSE" in your Application class to turn on as much logging as possible.

Does this recreate in any sample app?

**Comment by ghost** [comment]
@bryanlogan It is not reproducible. Logs shared in the original message are the only thing we have from Crashlytics/Play Console
