### ISSUE TITLE
Bug in Latest App boy sdk version 1.11.2 ,Every time when i open 'News Feed' 

### ISSUE THREAD

**Issue by shoaibahmad** [Appboy/appboy-android-sdk#47]
: FATAL EXCEPTION: main
                                                                                  Process: com.theentertainerme.entertainer, PID: 15984
                                                                                  android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                                      at android.view.ViewStub.inflate(ViewStub.java:264)
                                                                                      at com.appboy.ui.widget.BaseCardView.getProperViewFromInflatedStub(BaseCardView.java:271)
                                                                                      at com.appboy.ui.widget.ShortNewsCardView.<init>(ShortNewsCardView.java:37)
                                                                                      at com.appboy.ui.widget.ShortNewsCardView.<init>(ShortNewsCardView.java:27)
                                                                                      at com.appboy.ui.adapters.AppboyListAdapter.getView(AppboyListAdapter.java:109)
                                                                                      at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
                                                                                      at android.widget.AbsListView.obtainView(AbsListView.java:2823)
                                                                                      at android.widget.ListView.measureHeightOfChildren(ListView.java:1290)
                                                                                      at android.widget.ListView.onMeasure(ListView.java:1202)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:597)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1489)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:607)
                                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1238)
                                                                                      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:672)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                      at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
                                                                                      at android.view.View.measure(View.java:18586)
                                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:721..

**Comment by briancaw** [comment]
Hi @shoaibahmad 

We'll investigate this ASAP; can you let us know:

1)  If you are using Fresco or not, and if so, what version.
2) The make/model/OS-version of the device you saw this on.
3) What Appboy SDK version you are upgrading from (assuming it's an upgrade).

Thanks,
Appboy Android Team

**Comment by shoaibahmad** [comment]
Latest version of fresco and latest version of app boy sdk 1.11.2 Latest
and device is Samsung Note 4

**Comment by Bucimis** [comment]
Hi @shoaibahmad

Thanks for the information.  Appboy should work just fine with the latest version (0.9) of Fresco.

Are you calling `Fresco.initialize()` in your Application's `onCreate()` method?  If Fresco isn't initialized,
SimpleDraweeViews will fail to initialize as well.

Thanks,
Appboy Android Team

**Comment by shoaibahmad** [comment]
Thanks....Yes Its Fix on my Side

**Comment by briancaw** [comment]
Sounds good @shoaibahmad.  We'll revisit our documentation on this to make sure it's as clear as possible on this functionality.

Thanks,
Appboy Android Team
