### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by pinkred** [Appboy/appboy-android-sdk#55]
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:827)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:321)
       at android.app.NotificationManager.notify(NotificationManager.java:136)
       at android.support.v4.app.NotificationManagerCompatEclair.postNotification(NotificationManagerCompatEclair.java:30)
       at android.support.v4.app.NotificationManagerCompat$ImplEclair.postNotification(NotificationManagerCompat.java:152)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:225)
       at com.appboy.AppboyGcmReceiver.handleAppboyGcmMessage(AppboyGcmReceiver.java:132)
       at com.appboy.AppboyGcmReceiver$HandleAppboyGcmMessageTask.doInBackground(AppboyGcmReceiver.java:168)
       at com.appboy.AppboyGcmReceiver$HandleAppboyGcmMessageTask.doInBackground(AppboyGcmReceiver.java:156)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by briancaw** [comment]
Hi @pinkred,

Thanks very much for reporting this.  Can you let us know some additional information:

1) Is this issue reproducible?  If so, what are the steps to reproduce?  If not, how often are you seeing this issue?
2) What devices/OSes are you seeing this issue occur on?

Thanks,
Brian

**Comment by pinkred** [comment]
1) Fabric crashlytics 2 reports
2) OS 4.4.2 | LG-F200L | No rooted
    OS 6.0.1 | SM-N916S  | No rooted

Thanks.

**Comment by briancaw** [comment]
Hi @pinkred 

Apologies for the delay on this.  This should be handled/fixed on our most recent release - `1.15.0`.  If you are able confirm you on no longer seeing this issue on `1.15.0` or above it would be much appreciated.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi @pinkred,

Closing this for now.  Please reopen if you find this is not resolved.  Thanks again for reporting!

**Comment by saveenspringrole** [comment]
Hey did you resolve this issue with new version ? i  have got same issue "Fabric crashlytics reports". I was using 2.0+
