### ISSUE TITLE
Crash while clicking In-App message button: Android

### ISSUE THREAD

**Issue by sathish25** [Appboy/appboy-android-sdk#62]
Hi,

I have integrated latest Appboy version 1.15.3 in my app and I have noticed crash while selecting a button from In-App messages. On click behaviour button is configured to "Redirect to URL".

Due to this crash, I have added the below line in app manifest then it is working without any crash.
<activity android:name="com.appboy.ui.AppboyWebViewActivity" />

But none of the appboy documentation specify adding activity to manifest.

Please check the crash report below. 

Fatal Exception: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.app/com.appboy.ui.AppboyWebViewActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
       at android.app.Activity.startActivityForResult(Activity.java:3930)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.app.Activity.startActivityForResult(Activity.java:3890)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
       at android.app.Activity.startActivity(Activity.java:4213)
       at android.app.Activity.startActivity(Activity.java:4181)
       at com.appboy.ui.actions.WebAction.execute(WebAction.java:34)
       at com.appboy.ui.AppboyNavigator.gotoURI(AppboyNavigator.java:46)
       at com.appboy.ui.inappmessage.listeners.AppboyInAppMessageViewLifecycleListener.performClickAction(AppboyInAppMessageViewLifecycleListener.java:111)
       at com.appboy.ui.inappmessage.listeners.AppboyInAppMessageViewLifecycleListener.performInAppMessageButtonClicked(AppboyInAppMessageViewLifecycleListener.java:91)
       at com.appboy.ui.inappmessage.listeners.AppboyInAppMessageViewLifecycleListener.onButtonClicked(AppboyInAppMessageViewLifecycleListener.java:80)
       at com.appboy.ui.inappmessage.InAppMessageViewWrapper$3.onClick(InAppMessageViewWrapper.java:248)
       at android.view.View.performClick(View.java:5204)
       at android.view.View$PerformClick.run(View.java:21155)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by briancaw** [comment]
Hi @sathish25 

Please take a look at https://www.appboy.com/documentation/Android/#step-2-enabling-click-behaviors for guidance on how to solve this - i.e. you have to register our WebViewActivity in your ApplicationManifest so that it can be found when a click occurs.

Please let me know if you have any comments/questions about this.

Thanks,
Brian

**Comment by sathish25** [comment]
Thanks!!
