### ISSUE TITLE
 Could not setup connection 

### ISSUE THREAD

**Issue by Nammari** [Appboy/appboy-android-sdk#75]
Experienced exception processing API response. Failing task.
                                                                          bo.app.ao: Could not setup connection [https://leo.api.appboy.eu/api/v3/data] [failed to connect to leo.api.appboy.eu/151.101.37.5 (port 443) after 5000ms: isConnected failed: ENETUNREACH (Network is unreachable)].  Appboy will try to reconnect periodically.
                                                                              at bo.app.c.b(SourceFile:138)
                                                                              at bo.app.c.a(SourceFile:75)
                                                                              at bo.app.c.a(SourceFile:57)
                                                                              at bo.app.c.a(SourceFile:48)
                                                                              at bo.app.g.a(SourceFile:36)
                                                                              at bo.app.f.a(SourceFile:35)
                                                                              at bo.app.ci.a(SourceFile:88)
                                                                              at bo.app.ci.run(SourceFile:61)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.net.ConnectException: failed to connect to leo.api.appboy.eu/151.101.37.5 (port 443) after 5000ms: isConnected failed: ENETUNREACH (Network is unreachable)
                                                                              at libcore.io.IoBridge.isConnected(IoBridge.java:257)
                                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
                                                                              at libcore.io.IoBridge.connect(IoBridge.java:127)
                                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
                                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:457)
                                                                              at java.net.Socket.connect(Socket.java:927)
                                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                                              at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
                                                                              at com.android.okhttp.Connection.connect(Connection.java:167)
                                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209)
                                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:352)
                                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:341)
                                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:259)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:442)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
                                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
                                                                              at bo.app.c.a(SourceFile:152)
                                                                              at bo.app.c.b(SourceFile:135)
                                                                              at bo.app.c.a(SourceFile:75) 
                                                                              at bo.app.c.a(SourceFile:57) 
                                                                              at bo.app.c.a(SourceFile:48) 
                                                                              at bo.app.g.a(SourceFile:36) 
                                                                              at bo.app.f.a(SourceFile:35) 
                                                                              at bo.app.ci.a(SourceFile:88) 
                                                                              at bo.app.ci.run(SourceFile:61) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
                                                                           Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
                                                                              at libcore.io.IoBridge.isConnected(IoBridge.java:246)
                                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:193) 
                                                                              at libcore.io.IoBridge.connect(IoBridge.java:127) 
                                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188) 
                                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:457) 
                                                                              at java.net.Socket.connect(Socket.java:927) 
                                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
                                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
                                                                              at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79) 
                                                                              at com.android.okhttp.Connection.connect(Connection.java:167) 
                                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209) 
                                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:352) 
                                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:341) 
                                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:259) 
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:442) 
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245) 
                                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
                                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java) 
                                                                              at bo.app.c.a(SourceFile:152) 
                                                                              at bo.app.c.b(SourceFile:135) 
                                                                              at bo.app.c.a(SourceFile:75) 
                                                                              at bo.app.c.a(SourceFile:57) 
                                                                              at bo.app.c.a(SourceFile:48) 
                                                                              at bo.app.g.a(SourceFile:36) 
                                                                              at bo.app.f.a(SourceFile:35) 
                                                                              at bo.app.ci.a(SourceFile:88) 
                                                                              at bo.app.ci.run(SourceFile:61) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
04-13 17:30:38.796 22774-22861/com.exampleseller E/Appboy v2.0.0 .bo.app.ch: Error occurred while executing Appboy request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.

**Comment by Bucimis** [comment]
Hi @Nammari 

Thanks for filing this issue. Just to sanity check:
1) Is your device connected to the internet with airplane mode off? Is it possible to repro across devices?
2) Are you seeing this on v1.19.0 or only v2.0.0?
3) Did you change any network related settings on Appboy (automatic flush period, offline mode, etc)?

Thanks,
Jared

**Comment by Bucimis** [comment]
HI @Nammari 

Were you able to solve this issue?  We'd be happy to provide any additional assistance, otherwise, we'll close this issue out soon for lack of activity.

Thanks,
Jared

**Comment by briancaw** [comment]
Hi @Nammari 

Closing this issue for now - please let us know if you continue to have any issues getting things working and we'd be happy to help resolve ASAP.

Thanks,
Brian
