### ISSUE TITLE
IllegalStateException: Not allowed to start service Intent for Android O Notifications while in background

### ISSUE THREAD

**Issue by theyhoang** [Appboy/appboy-android-sdk#81]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Appboy Android SDK are you using?

2.1.3

## What did you do?

We have had appboy integrated properly and this problem is on an Android O device. Put app in background and attempt to submit a notification to user/device. Logcat reports a "IllegalStateException: Not allowed to start service Intent".

## What did you expect to happen?

Devices running Android O should not be crashing when receiving a notification.

## What happened instead?

App crashes while in background receiving notification.

## Steps to reproduce

- Put app in background
- Attempt to submit a notification to user/device. 
- Logcat reports a "IllegalStateException: Not allowed to start service Intent".

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No customizations applied, notifications work for device pre-O.

**Comment by radixdev** [comment]
Hello @theyhoang,

We're having difficulty reproducing the issue and have some additional questions.
1. On what device are you seeing the crash?
2. Is the device running a DP or the released Android O?
3. Can you share the full stacktrace/logcat of the crash? Please be sure to set `AppboyLogger.setLogLevel(Log.VERBOSE)` before the crash for the full output.
4. Have you integrated other features such as in-app messages, feed, etc.?

Thank you,
Julian

**Comment by theyhoang** [comment]
Hello @radixdev, 

1. We are seeing it on the emulator and a Nexus 6P. It does not happen on every push notification, but re-trying the push notification a couple of times will surface the issue.

2. Released Android O

3. 
```
09-15 14:39:13.776 6417-6417/? I/Appboy v2.1.3 .com.appboy.AppboyGcmReceiver: Received broadcast message. Message: Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.hollar.android.qa2 cmp=com.hollar.android.qa2/com.appboy.AppboyGcmReceiver (has extras) }
09-15 14:39:13.778 6417-6452/? I/Appboy v2.1.3 .com.appboy.AppboyGcmReceiver: Push message payload received: Bundle[{google.sent_time=1505511566735, a=break, p=0, t=Hollar Android QA2, _ab=true, from=625083566932, ab_nc=com_appboy_default_notification_channel, google.message_id=0:1505511566737323%5cb307faf7a90110, collapse_key=campaign}]
09-15 14:39:13.778 6417-6452/? D/Appboy v2.1.3 .com.appboy.AppboyGcmReceiver: Received notification push
09-15 14:39:13.778 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Message without notification id provided in the extras bundle received. Using a hash of the message: 511583382
09-15 14:39:13.790 6417-6417/? D/AndroidRuntime: Shutting down VM
09-15 14:39:13.794 6417-6439/? E/GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
09-15 14:39:13.795 6417-6417/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.hollar.android.qa2, PID: 6417
                                                 java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.hollar.android.qa2 cmp=com.hollar.android.qa2/com.google.firebase.messaging.FirebaseMessagingService (has extras) }: app is in background uid UidRecord{227a2a5 u0a84 RCVR idle procs:1 seq(0,0,0)}
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.hollar.android.qa2 cmp=com.hollar.android.qa2/com.google.firebase.messaging.FirebaseMessagingService (has extras) }: app is in background uid UidRecord{227a2a5 u0a84 RCVR idle procs:1 seq(0,0,0)}
                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                     at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                     at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
                                                     at com.google.firebase.iid.zzg.zzg(Unknown Source:9)
                                                     at com.google.firebase.iid.zzg.zzb(Unknown Source:76)
                                                     at com.google.firebase.iid.FirebaseInstanceIdReceiver.zza(Unknown Source:4)
                                                     at com.google.firebase.iid.FirebaseInstanceIdReceiver.onReceive(Unknown Source:106)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-15 14:39:13.798 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting title for notification
09-15 14:39:13.798 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting content for notification
09-15 14:39:13.801 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting ticker for notification
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting small icon for notification via resource id
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Large icon bitmap url not present in extras. Attempting to use resource id instead.
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Large icon resource id not present for notification
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Large icon not set for notification
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Sound key not present in notification extras. Not setting sound for notification.
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Summary text not present in notification extras. Not setting summary text for notification.
09-15 14:39:13.807 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting priority for notification
09-15 14:39:13.808 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Setting style for notification
09-15 14:39:13.808 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationStyleFactory: Rendering push notification with BigTextStyle
09-15 14:39:13.810 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Using default accent color for notification
09-15 14:39:13.811 6417-6452/? D/Appboy v2.1.3 .com.appboy.configuration.CachedConfigurationProvider: Unable to find the xml integer configuration value with key com_appboy_default_notification_accent_color. Using default value '0'.
09-15 14:39:13.811 6417-6452/? D/Appboy v2.1.3 .com.appboy.configuration.CachedConfigurationProvider: Defaulting to using xml value for key: com_appboy_default_notification_accent_color and value: 0
09-15 14:39:13.811 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Category not present in notification extras. Not setting category for notification.
09-15 14:39:13.813 6417-6452/? D/Appboy v2.1.3 .com.appboy.push.AppboyNotificationUtils: Using extras provided notification channel with id: com_appboy_default_notification_channel
```
4. Yes we have event reporting and in-app messages.

**Comment by radixdev** [comment]
What is your firebase dependency version in your `build.gradle`? From [the firebase release notes](https://firebase.google.com/support/release-notes/android), they state that support for Android O was first released in 10.2.1 (although I'd recommend using the most recent version).

**Comment by theyhoang** [comment]
`10.2.0` I'll try upgrading to see if this resolves the issue.

**Comment by radixdev** [comment]
Hey @theyhoang ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Comment by samirmangroliya** [comment]
please add new firebase messaging  dependencies for android O

     compile 'com.google.firebase:firebase-messaging:11.4.0'

upgrade google play services and google repositories if needed.

**Comment by Codepeaker** [comment]
is this issue solved by upgrading Firebase?

**Comment by samirmangroliya** [comment]
yes
