### ISSUE TITLE
Push Notifications Android 8.0.0 Crash

### ISSUE THREAD

**Issue by beast-shubham** [Appboy/appboy-android-sdk#82]
* [YES] I have checked [Appboy's documentation](https://www.appboy.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Appboy Android SDK are you using?

2.1.+

## What did you do?

Appboy was already added to the app. If I send Push Notifications to a user through Campaigns or personally to a specific user, my app crashes on devices running ANDROID O, ie, Android 8.0.0

## What did you expect to happen?

The User should have received Push Notifications without experiencing a crash

## What happened instead?

there is a crash in Android O when Push Notifications are sent, in both cases when the app is active and when it is not active. 

## Steps to reproduce

- Just sending normal push notifications (without any key-value pairs) crashes the app on Android O.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

## Project that demonstrates the issue

The crash encountered is - 

`
com.ABCDE.client E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                     Process: com.ABCDE.client, PID: 13706
                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                         at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                         at java.lang.Thread.run(Thread.java:764)
                                      Caused by: java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.ABCDE.client-Hp-cC3Wm_DPKpZ-_rI4TcA==/split_lib_dependencies_apk.apk:classes36.dex)
                                         at com.appboy.push.AppboyNotificationUtils.setNotificationChannelIfSupported(AppboyNotificationUtils.java:775)
                                         at com.appboy.push.AppboyNotificationFactory.populateNotificationBuilder(AppboyNotificationFactory.java:81)
                                         at com.appboy.push.AppboyNotificationFactory.createNotification(AppboyNotificationFactory.java:97)
                                         at com.appboy.AppboyGcmReceiver.handleAppboyGcmMessage(AppboyGcmReceiver.java:127)
                                         at com.appboy.AppboyGcmReceiver$HandleAppboyGcmMessageTask.doInBackground(AppboyGcmReceiver.java:173)
                                         at com.appboy.AppboyGcmReceiver$HandleAppboyGcmMessageTask.doInBackground(AppboyGcmReceiver.java:160)
                                         at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                         at java.lang.Thread.run(Thread.java:764) 
`

**Comment by Bucimis** [comment]
Hi @beast-shubham,

What version of the v4 support library are you using?  Android O support requires version 26.0.0+.

Thanks,
Appboy Android Team

**Comment by beast-shubham** [comment]
Hi @Bucimis ,
Thank you for the expedite reply. 

So I hadn't specified any specific version number for v4 (I assumed it would be latest by default), but after this, I tried adding the line
`compile 'com.android.support:support-v4:26.0.1'`
, and I still face the crash. 

Any other recommendations?

**Comment by cuongloveit** [comment]
I also have this issue.
Wait...... :)

**Comment by Bucimis** [comment]
Hi @beast-shubham,

Unfortunately we were still not able to reproduce on our end using `26.0.1`. Could you double check that the version of the v4 support library that made it into the APK was `26.0.1`?  Perhaps an older version of v4 is being included by some other library, or the build wasn't fully cleaned.

Note that `setChannelId(String)` was added to `NotificationCompat.Builder` in `26.0.0` (https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setChannelId(java.lang.String)) and should be present in `26.0.1` as well.

If this doesn't resolve the issue, it would also be great if you could send a sample project reproducing the issue to us so that we can debug as well.

Thanks,
Appboy Android Team

**Comment by beast-shubham** [comment]
hey @Bucimis ,
So I resolved this issue, with the comment you just made. Thank you so much for the above reply. 

Basically, I was making a minor change in v4 for another SDK I was using and removing that fixed the crash. In conclusion, it was me using v4 25.0.1 which was crashing the app. 

Thank you so much for helping me out.

**Comment by Bucimis** [comment]
Sure thing @beast-shubham!  Glad its working :)
