### ISSUE TITLE
Logging Error

### ISSUE THREAD

**Issue by shaishavgandhi05** [Appboy/appboy-android-sdk#89]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
2.1.4

## What did you do?

Register Appboy for lifecycle listeners. The error occurs on all app starts

## What did you expect to happen?

Shouldn't log IO exception

## What happened instead?

Logs an IO exception in logger

## Steps to reproduce

Start the app. The following stacktrace prints out. 

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Here's the stack trace
```
E/Appboy v2.1.4 .bo.app.dz: Caught exception while trying to read Appboy logger tag from system properties.
                                                                             java.io.IOException: Cannot run program "/system/bin/getprop": error=13, Permission denied
                                                                                 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
                                                                                 at java.lang.Runtime.exec(Runtime.java:692)
                                                                                 at java.lang.Runtime.exec(Runtime.java:560)
                                                                                 at bo.app.dz.a(SourceFile:22)
                                                                                 at com.appboy.support.AppboyLogger.checkForSystemLogLevelProperty(SourceFile:28)
                                                                                 at com.appboy.Appboy$1.run(SourceFile:209)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                 at java.lang.Thread.run(Thread.java:764)
                                                                              Caused by: java.io.IOException: error=13, Permission denied
                                                                                 at java.lang.UNIXProcess.forkAndExec(Native Method)
                                                                                 at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
                                                                                 at java.lang.ProcessImpl.start(ProcessImpl.java:128)
                                                                                 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
                                                                                 at java.lang.Runtime.exec(Runtime.java:692) 
                                                                                 at java.lang.Runtime.exec(Runtime.java:560) 
                                                                                 at bo.app.dz.a(SourceFile:22) 
                                                                                 at com.appboy.support.AppboyLogger.checkForSystemLogLevelProperty(SourceFile:28) 
                                                                                 at com.appboy.Appboy$1.run(SourceFile:209) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                 at java.lang.Thread.run(Thread.java:764) ```

**Comment by radixdev** [comment]
Hey @shaishavgandhi05 ,

Thanks for filing this issue. This log is harmless and shouldn't interfere with the lifecycle listener or any other Braze functionality. You can suppress all logs from the SDK [using the AppboyLogger](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/support/AppboyLogger.html#setLogLevel-int-).

The above should suffice for not seeing the log any further. For debugging purposes:
1. What device model did you see the error on? API version?
2. Is the device rooted or on stock?

Thanks,
Julian

**Comment by shaishavgandhi05** [comment]
Ok that's helpful. Just wanted to bring it up in case it was something. 

1. Android Emulator. Nexus 5X. API 26
2. Device is stock.

**Comment by radixdev** [comment]
Hey @shaishavgandhi05 ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
